name: Docker Compose Workflow

on:
  push:
    branches:
      - main

jobs:
  test-docker-compose:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and run Docker Compose
      run: |
        docker-compose -f deploy/docker-compose.yaml up -d
        sleep 10

    - name: Check if containers are running
      run: docker-compose ps

    - name: Stop Docker Compose
      run: docker-compose -f deploy/docker-compose.yaml down
